password = "egspidr1"



[token_info]
token = "ya29.a0AfB_byBSIgRnGKNebRP6hrlMOzWiKu4ntwPfCr5VpvmCMj9fUb6MLGY2fy4HgdFwV9rXFT2BFmslavH79qlu8_8AVw3KZqMsj8-OqkIbkLnJY3lNKcCg4y7XrhwTeEaOT_whNLp4BSeMoyzS2nFxGUUPmeeKUIUyepJ6Ly0aCgYKAXESARMSFQHGX2MiwCH2HsQNLh1rkwsZkYPsPg0174"
refresh_token = "1//0hS71RX5YlCA-CgYIARAAGBESNwF-L9Ir5sHlloVOl6GbMy5hoke6RtBM9_GNdqV9Vg7sv5g2YkaV1h3lgZn1oDM7E3eaewWAOsA"
token_uri = "https://oauth2.googleapis.com/token"
client_id = "964295874800-vsnj6qi4kva0t235nodiugm9ev02msm4.apps.googleusercontent.com"
client_secret = "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"
scopes = ["https://www.googleapis.com/auth/spreadsheets.readonly"] 
expiry = "2023-11-14T17:36:07.266843Z"

[creds_info]
client_id = "964295874800-vsnj6qi4kva0t235nodiugm9ev02msm4.apps.googleusercontent.com"
project_id = "direct-beacon-384919"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"
redirect_uris = ["http://localhost"]






[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/144cc9bZWC7VVwio5o9njr2TpiiptNMvrWWKuixBUlBA/edit#gid=2139161262"
worksheet = "TIME"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
type = "service_account"  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
project_id = "bycubes-tracker"
private_key_id = "87defed04018f9113a5ca52c082fff0c877a11a2"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC+A/2cjYz+5i6c\nFcQRNDFtYMWhJn37rX1MILTLkCsTYSK0VXZbwmr4X5A9vruV7l25fSdf7UXYGpql\nZZqEBv1UuIjr9leU6OEAr+me6qK/2IOpRTvMjsFrwFUSkhsMX3B51UH0vQ6zVc7S\nu6HxViXW1OULfdVt0OK823jweagIGgtGZVUijh+6FJ4TyMVLxKDedeAKgV/7wiLL\n5Rl46elF5yTH+Ymwgbs6DYUh4/JpMSxa3DUI2/mrO12586wTx7ba/hvi7BZz684y\n/kemrybQzMAcp/lymApf4NkN3jhQbvFew54vy0T5aMyJxuYqBBDhhZyvnA+yn4zQ\nY1CzhRn/AgMBAAECggEAM2oXBHZUsWANOpS1IcaSnTrzHsCwlBoEbkXnRbFzxmGh\nJ1R8myWHFj+dYueqEE6YM6mGrvEf1fKU564PWiwd/f+UpOxaFGPTBgGTYDmy4eAu\n9+1Q2e/CrGo1WroH8ZgdcgnfN960DJhqRyEYF5os0O14MFzTFEzSHTHxjngMnGwg\nRvJMBPlLTs3UJTNsreL9n2npO8tk/VHhJQNWb0yK50Da7EfTLuPExqm7dRFcLHvG\nCCFoHBR0YgggL2PkuvqcXVY3SPGloCaDBK0F2r6LaEss0rXY6nJun+eSChpwa6fP\neEMxdT1TYCtlT9c2rlSrlai8b/VWaUD08cOlpnW2KQKBgQDd9pCFq4+/L6IFbbfy\ndnY9rMeuFk06aO+y9ZK9s6wEn45ThqD4p+V6v5A4tJ6009MaoFai7ww1gslXKnVx\nStiGCJlr/wz60CYJ0y/eG77gahbU4RYv4qzUS8wedBr7gtIWHjl5TEpfURU7wF5P\nCnEQ/LG9kHSJjU3dDEwfGqCE5QKBgQDbJ0kjnEc7vbk/ojeou3hJ9BZUZ0Cfdr7E\nkNUhihioq26ZbYoP541B32C6LMkvd4ruFiwBCYid/uPlghwEbxAk2tg6CzYqWnLB\nbTAuneqoNbvsN00TXv0rRnJVyCPHxCdQVHd3rMr2EIRWzpG2RObNy4Bp370btl7O\nbs51Fe95EwKBgQCaevxiy+Cjw1cUSCR6D5CDpDjlJIhjWp1ZBCk49k+GeDXqVAy8\ngr3oDGMn1C2Q1Mxb/7PMemsY4wmWLOrICrtfraR50W0LMssGk4EBKHZUYgG5714t\nvaljp81MdKpC2e21jxuZHEu2wwvwJhZ9FFtU40ohEOTKxxml+uUP0MxfMQKBgQDD\n9a/vmKkVYUNJBBsy1FbuAcUJub3OGRbhmwQI1nvQLmJZ7Nm7+PeVRFEwiCVpPUJM\nPCUi1EyFwkoziZDV4h2UZt9bn3TSkEf2b1TbCjeuK0YbJSPVQ2WrkXVhAPIFiX8B\n1FVy/F4Lgp9jI5ilW5zpvaLYiMiHBB5oBiq0BWY5YwKBgQCj7okMoo+BAjzIxkrO\np83pHeH06iCS5gJEgP17JcKS4OS92tZFaJ8jqTKSmrLUrUwmSSlfSI175IalQmae\noZEkWtNt6WAv/LCkYJpqYL1kWrbM7sbGIAxdivfJsmHZiFE/BA3XLiSmJ0tR6CcH\nedh3AuQb46cfusFbUvSzEhbfBQ==\n-----END PRIVATE KEY-----\n"
client_email = "python-ac@bycubes-tracker.iam.gserviceaccount.com"
client_id = "106419605819871858570"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/python-ac%40bycubes-tracker.iam.gserviceaccount.com"